// <auto-generated />
using GlobalShipping.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalShipping.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422065019_AddMaxWeightToCountry")]
    partial class AddMaxWeightToCountry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GlobalShipping.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseShippingRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseShippingRate = 5.0m,
                            Code = "IN",
                            IsActive = true,
                            MaxWeight = 50.0m,
                            Name = "India"
                        },
                        new
                        {
                            Id = 2,
                            BaseShippingRate = 8.0m,
                            Code = "US",
                            IsActive = true,
                            MaxWeight = 100.0m,
                            Name = "Estados Unidos"
                        },
                        new
                        {
                            Id = 3,
                            BaseShippingRate = 10.0m,
                            Code = "UK",
                            IsActive = true,
                            MaxWeight = 70.0m,
                            Name = "Reino Unido"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
